In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("employee_turnover.csv")

In [3]:
df.head(5)

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
0,0.562326,0.141129,0.123989,0.347583,0.330353,0.328853,0.600933,0.315990,0.768736,0.090671,0.324786,0.669193,0.602932,0.105486,0.217344,0
1,0.017041,0.559047,0.511203,0.793908,0.423550,0.553450,0.742009,0.897146,0.380035,0.601633,0.694611,0.043271,0.800761,0.482484,0.030056,0
2,0.774699,0.604371,0.798174,0.260500,0.804034,0.131800,0.775178,0.830947,0.218726,0.972936,0.153476,0.701336,0.705275,0.023555,0.107638,1
3,0.628174,0.385249,0.230104,0.516809,0.272248,0.589249,0.482409,0.090507,0.402746,0.132842,0.305973,0.549688,0.600531,0.093620,0.168190,0
4,0.799183,0.199967,0.839029,0.247927,0.341934,0.076818,0.055356,0.680860,0.923341,0.493017,0.844094,0.793751,0.664679,0.712494,0.670000,0

In [4]:
# df.info
df.isnull().count()

Job_Satisfaction                           1350
Performance_Rating                         1350
Years_At_Company                           1350
Work_Life_Balance                          1350
Distance_From_Home                         1350
Monthly_Income                             1350
Education_Level                            1350
Age                                        1350
Num_Companies_Worked                       1350
Employee_Role                              1350
Annual_Bonus                               1350
Training_Hours                             1350
Department                                 1350
Annual_Bonus_Squared                       1350
Annual_Bonus_Training_Hours_Interaction    1350
Employee_Turnover                          1350
dtype: int64

In [5]:
df.sample(5)

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
7,0.031835,0.775622,0.126102,0.780592,0.616668,0.474318,0.480459,0.092658,0.222781,0.642847,0.873098,0.237203,0.084777,0.762300,0.207101,0
61,0.335672,0.668155,0.287798,0.187104,0.300733,0.886993,0.460883,0.225415,0.321439,0.002771,0.755808,0.225677,0.597921,0.571246,0.170569,0
711,0.370853,0.197054,0.459856,0.044612,0.799796,0.076956,0.518835,0.306810,0.577543,0.959433,0.645570,0.035362,0.430402,0.416761,0.022829,0
1264,0.381545,0.357699,0.602211,0.596519,0.713777,0.716626,0.029733,0.541852,0.665817,0.779171,0.888672,0.326006,0.393805,0.789738,0.289712,0
1097,0.660947,0.672127,0.803381,0.774872,0.473254,0.104813,0.814336,0.601774,0.033013,0.788491,0.393339,0.314113,0.515048,0.154716,0.123553,1

In [17]:
# NOW WE NEED TO CONVERT THE DATA INTO X AND Y

X = df.drop(columns = ['Employee_Turnover'])
y = df['Employee_Turnover']

In [19]:
X.head()

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction
0,0.562326,0.141129,0.123989,0.347583,0.330353,0.328853,0.600933,0.315990,0.768736,0.090671,0.324786,0.669193,0.602932,0.105486,0.217344
1,0.017041,0.559047,0.511203,0.793908,0.423550,0.553450,0.742009,0.897146,0.380035,0.601633,0.694611,0.043271,0.800761,0.482484,0.030056
2,0.774699,0.604371,0.798174,0.260500,0.804034,0.131800,0.775178,0.830947,0.218726,0.972936,0.153476,0.701336,0.705275,0.023555,0.107638
3,0.628174,0.385249,0.230104,0.516809,0.272248,0.589249,0.482409,0.090507,0.402746,0.132842,0.305973,0.549688,0.600531,0.093620,0.168190
4,0.799183,0.199967,0.839029,0.247927,0.341934,0.076818,0.055356,0.680860,0.923341,0.493017,0.844094,0.793751,0.664679,0.712494,0.670000

In [21]:
# Now We Split the data into train and test data 
from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(
    X, y, random_state = 42, test_size = 0.2
)

In [27]:
# X_train # to see the data was split or not

# Now Import the model to train the model

from sklearn.linear_model import LogisticRegression

In [32]:
# Train the model 

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [34]:
# Predict the output fron the data and check the accuracy score 
from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)

print(accuracy_score(y_pred, y_test))

0.8592592592592593