In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("loan_approval_data.csv")

In [3]:
df.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes

In [4]:
df.shape

(1000, 20)

In [5]:
df.isnull().sum()

Applicant_ID          50
Applicant_Income      50
Coapplicant_Income    50
Employment_Status     50
Age                   50
Marital_Status        50
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose          50
Property_Area         50
Education_Level       50
Gender                50
Employer_Category     50
Loan_Approved         50
dtype: int64

In [6]:
df.sample(10)

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
526,527.0,9483.0,6563.0,Salaried,59.0,Married,2.0,701.0,3.0,0.35,17573.0,18643.0,NaN,48.0,Home,Urban,Graduate,Male,Business,Yes
193,194.0,13835.0,2033.0,Contract,57.0,Married,1.0,574.0,0.0,0.16,NaN,35050.0,30158.0,24.0,Car,Urban,Not Graduate,Male,Government,No
626,627.0,9350.0,6294.0,Self-employed,42.0,Single,0.0,620.0,1.0,0.37,14067.0,37888.0,22292.0,72.0,Car,Urban,Graduate,Male,Unemployed,No
467,NaN,19575.0,6917.0,Salaried,NaN,Single,0.0,591.0,2.0,0.23,16814.0,15447.0,5597.0,60.0,Car,Urban,Graduate,Female,Government,No
704,705.0,NaN,NaN,Contract,NaN,Single,3.0,627.0,4.0,0.50,296.0,44610.0,22804.0,24.0,Home,Urban,Not Graduate,Male,MNC,No
759,760.0,8988.0,7285.0,Salaried,51.0,Married,3.0,560.0,1.0,0.54,17342.0,33370.0,9266.0,84.0,Business,Urban,Graduate,Male,Business,No
625,626.0,19144.0,7595.0,Salaried,28.0,Married,0.0,745.0,0.0,0.32,234.0,26415.0,17005.0,36.0,Home,Urban,Graduate,NaN,MNC,Yes
957,958.0,12998.0,1179.0,Self-employed,33.0,Married,3.0,767.0,0.0,0.55,6044.0,18013.0,39278.0,12.0,Personal,Rural,Graduate,Male,Private,No
489,490.0,8530.0,4109.0,Self-employed,58.0,Single,1.0,585.0,4.0,0.20,2892.0,3598.0,16256.0,84.0,Car,Urban,Not Graduate,Male,Government,No
440,441.0,6360.0,8783.0,Salaried,53.0,Married,1.0,786.0,1.0,NaN,7855.0,20598.0,31279.0,36.0,Business,Urban,Not Graduate,Male,Government,No

In [7]:
df.columns

Index(['Applicant_ID', 'Applicant_Income', 'Coapplicant_Income',
       'Employment_Status', 'Age', 'Marital_Status', 'Dependents',
       'Credit_Score', 'Existing_Loans', 'DTI_Ratio', 'Savings',
       'Collateral_Value', 'Loan_Amount', 'Loan_Term', 'Loan_Purpose',
       'Property_Area', 'Education_Level', 'Gender', 'Employer_Category',
       'Loan_Approved'],
      dtype='object')

In [8]:
df['Loan_Approved'].value_counts()

Loan_Approved
No     652
Yes    298
Name: count, dtype: int64

In [9]:
for col in df.columns:
    print(col)

Applicant_ID
Applicant_Income
Coapplicant_Income
Employment_Status
Age
Marital_Status
Dependents
Credit_Score
Existing_Loans
DTI_Ratio
Savings
Collateral_Value
Loan_Amount
Loan_Term
Loan_Purpose
Property_Area
Education_Level
Gender
Employer_Category
Loan_Approved

In [10]:
df.dtypes

Applicant_ID          float64
Applicant_Income      float64
Coapplicant_Income    float64
Employment_Status      object
Age                   float64
Marital_Status         object
Dependents            float64
Credit_Score          float64
Existing_Loans        float64
DTI_Ratio             float64
Savings               float64
Collateral_Value      float64
Loan_Amount           float64
Loan_Term             float64
Loan_Purpose           object
Property_Area          object
Education_Level        object
Gender                 object
Employer_Category      object
Loan_Approved          object
dtype: object

In [11]:
num_col = df.select_dtypes(include = ['float']).columns

In [12]:
num_col

Index(['Applicant_ID', 'Applicant_Income', 'Coapplicant_Income', 'Age',
       'Dependents', 'Credit_Score', 'Existing_Loans', 'DTI_Ratio', 'Savings',
       'Collateral_Value', 'Loan_Amount', 'Loan_Term'],
      dtype='object')

In [13]:
cat_col = df.select_dtypes(include = ['object']).columns

In [14]:
cat_col

Index(['Employment_Status', 'Marital_Status', 'Loan_Purpose', 'Property_Area',
       'Education_Level', 'Gender', 'Employer_Category', 'Loan_Approved'],
      dtype='object')

In [15]:
for col in num_col:
    df[col] = df[col].fillna(df[col].mean())

In [16]:
for col in cat_col:
    df[col] = df[col].fillna(df[col].mode()[0])

In [17]:
# df.sample(12)
df.isnull().sum()

Applicant_ID          0
Applicant_Income      0
Coapplicant_Income    0
Employment_Status     0
Age                   0
Marital_Status        0
Dependents            0
Credit_Score          0
Existing_Loans        0
DTI_Ratio             0
Savings               0
Collateral_Value      0
Loan_Amount           0
Loan_Term             0
Loan_Purpose          0
Property_Area         0
Education_Level       0
Gender                0
Employer_Category     0
Loan_Approved         0
dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
label_encoding_colums = ['Gender', 'Education_Level','Loan_Approved']
for col in label_encoding_colums:
    df[col] = le.fit_transform(df[col])

In [19]:
df

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.000000,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.000000,45638.0,16619.0,84.0,Personal,Urban,1,0,Private,0
1,2.0,2860.000000,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.000000,49272.0,38687.0,48.0,Car,Semiurban,0,1,Private,0
2,3.0,7390.000000,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.000000,6908.0,27943.0,72.0,Business,Urban,0,0,Government,1
3,4.0,13964.000000,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.000000,10844.0,27819.0,60.0,Business,Rural,0,0,Government,0
4,5.0,13284.000000,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.000000,37629.0,12741.0,72.0,Car,Urban,0,1,Private,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996.0,10852.571579,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.000000,43563.0,8311.0,72.0,Personal,Urban,1,1,Unemployed,0
996,997.0,3279.000000,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,9940.452632,18361.0,22563.0,12.0,Business,Urban,0,0,Government,0
997,998.0,15192.000000,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.000000,41335.0,16203.0,24.0,Home,Rural,0,1,MNC,0
998,999.0,9083.000000,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.000000,8933.0,10290.0,36.0,Personal,Urban,0,1,Private,1
999,1000.0,13093.000000,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.000000,25816.0,35818.0,48.0,Personal,Semiurban,0,1,Private,0

In [20]:
df = pd.get_dummies(df, columns = ["Employment_Status", "Marital_Status", "Loan_Purpose", "Property_Area", "Employer_Category"], dtype = int)

In [21]:
df.columns

Index(['Applicant_ID', 'Applicant_Income', 'Coapplicant_Income', 'Age',
       'Dependents', 'Credit_Score', 'Existing_Loans', 'DTI_Ratio', 'Savings',
       'Collateral_Value', 'Loan_Amount', 'Loan_Term', 'Education_Level',
       'Gender', 'Loan_Approved', 'Employment_Status_Contract',
       'Employment_Status_Salaried', 'Employment_Status_Self-employed',
       'Employment_Status_Unemployed', 'Marital_Status_Married',
       'Marital_Status_Single', 'Loan_Purpose_Business', 'Loan_Purpose_Car',
       'Loan_Purpose_Education', 'Loan_Purpose_Home', 'Loan_Purpose_Personal',
       'Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban',
       'Employer_Category_Business', 'Employer_Category_Government',
       'Employer_Category_MNC', 'Employer_Category_Private',
       'Employer_Category_Unemployed'],
      dtype='object')

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
cols = ['Applicant_Income', 'Coapplicant_Income',
        'Credit_Score', 'Savings',
       'Collateral_Value', 'Loan_Amount', 'Loan_Term']

for col in cols:
    df[col] = scaler.fit_transform(df[[col]])

In [23]:
# CONVERT THE DATA INTO X AND Y

X = df.drop(['Applicant_ID', 'Loan_Approved'], axis = 1)
y = df['Loan_Approved']

In [24]:
X

,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,...,Loan_Purpose_Home,Loan_Purpose_Personal,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Employer_Category_Business,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed
0,1.407951,-1.288905,51.0,0.0,-0.561612,4.0,0.53,1.657382,1.490881,-0.348340,...,0,1,0,0,1,0,0,0,1,0
1,-1.620925,-0.838280,46.0,3.0,-0.791819,2.0,0.30,-1.289197,1.750915,1.620796,...,0,0,0,1,0,0,0,0,1,0
2,-0.702223,-1.038131,25.0,2.0,-0.029260,4.0,0.20,0.683713,-1.280477,0.662105,...,0,0,0,0,1,0,1,0,0,0
3,0.631010,1.077923,40.0,2.0,-1.396110,3.0,0.31,-0.067863,-0.998834,0.651040,...,0,0,1,0,0,0,1,0,0,0
4,0.493103,-0.299762,31.0,2.0,0.646971,1.0,0.29,-0.097113,0.917790,-0.694375,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.000000,1.398453,58.0,0.0,-1.712644,0.0,0.59,-0.800523,1.342403,-1.089666,...,0,1,0,0,1,0,0,0,0,1
996,-1.535950,0.444188,58.0,1.0,-0.432121,3.0,0.19,0.000000,-0.460948,0.182046,...,0,0,0,0,1,0,1,0,0,0
997,0.880053,1.168606,48.0,1.0,-0.144364,1.0,0.40,-0.238111,1.182976,-0.385460,...,1,0,1,0,0,0,0,1,0,0
998,-0.358876,0.801340,50.0,1.0,1.035444,3.0,0.31,0.621885,-1.135577,-0.913079,...,0,1,0,0,1,0,0,0,1,0
999,0.454368,-0.940821,23.0,1.0,-0.906922,3.0,0.32,0.437100,0.072501,1.364794,...,0,1,0,1,0,0,0,0,1,0

In [25]:
# SPLIT THE DATA INTO TRAIN AND TEST SETS

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [26]:
X_train.head()

,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,...,Loan_Purpose_Home,Loan_Purpose_Personal,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Employer_Category_Business,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed
29,-1.006429,1.031884,31.000000,0.0,-1.050801,0.000000,0.11,0.344269,-1.191605e+00,7.820305e-01,...,0,0,1,0,0,0,1,0,0,0
535,-1.231744,-1.588159,50.000000,0.0,-0.892534,0.000000,0.21,-0.800698,-1.386237e+00,-5.118990e-01,...,1,0,0,0,1,1,0,0,0,0
695,0.000000,1.340904,36.000000,0.0,-1.324171,4.000000,0.22,-1.183055,2.603187e-16,-3.246182e-16,...,0,1,0,1,0,0,0,0,1,0
557,-1.717459,-1.035690,39.971579,1.0,0.718910,4.000000,0.34,0.340066,1.698680e+00,-6.434245e-01,...,1,0,0,0,1,0,1,0,0,0
836,-1.140685,0.058087,42.000000,1.0,0.000000,1.950526,0.18,1.353669,2.603187e-16,-5.904217e-01,...,1,0,0,0,1,0,0,0,1,0

In [27]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(random_state = 42)

model.fit(X_train, y_train)

GradientBoostingRegressor(random_state=42)

In [28]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

pred = model.predict(X_test)
print(mean_squared_error(y_test, pred))

0.07394899626574157

In [29]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

model = GradientBoostingRegressor()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE : 0.14715875112089802
MSE : 0.07388068000465625
RMSE: 0.27181000718269416
R2 Score: 0.6514651255824685